import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarData from './components/NavbarData'
import FooterData from "./components/FooterData";
import Topbar from "./components/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Topbar/>
        <NavbarData/>
        {children}
        <FooterData />
      </body>
    </html>
  );
}
